blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('', BlogDetailView.as_view(), name='blog_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls', namespace='service')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from service.apps import ServiceConfig
from service.views import (HomeTemplateView, CustomerListView, MailingListView, MessageListView, MessageDetailView,
                           MailingCreateView, MessageDeleteView, CustomerCreateView, CustomerDetailView,
                           CustomerUpdateView, CustomerDeleteView, MessageCreateView, MessageUpdateView,
                           MailingDetailView, MailingUpdateView, MailingDeleteView, get_report, LogListView,
                           mailing_toggle_activity)

app_name = ServiceConfig.name

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),

    path('customers/', CustomerListView.as_view(), name='customers'),
    path('customers/create/', CustomerCreateView.as_view(), name='customer_create'),
    path('customers/<slug:slug>/', CustomerDetailView.as_view(), name='customer'),
    path('customers/<slug:slug>/update/', CustomerUpdateView.as_view(), name='customer_update'),
    path('customers/<slug:slug>/delete/', CustomerDeleteView.as_view(), name='customer_delete'),

    path('messages/', MessageListView.as_view(), name='messages'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/<slug:slug>/', MessageDetailView.as_view(), name='message'),
    path('messages/<slug:slug>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('messages/<slug:slug>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('services/', MailingListView.as_view(), name='mailings'),
    path('services/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('services/<slug:slug>/', MailingDetailView.as_view(), name='mailing'),
    path('services/<slug:slug>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('services/<slug:slug>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),

    path('report/', get_report, name='report'),
    path('services/<slug:slug>/logs/', LogListView.as_view(), name='logs'),
    path('services/<slug:slug>/activity/', mailing_toggle_activity, name='mailing_activity'),
]

service/models.py
from slugify import slugify

from django.db import models

from config import settings

NULLABLE = {'null': True, 'blank': True}


class Customer(models.Model):
    """Модель для работы с клиентами"""

    name = models.CharField(max_length=150, verbose_name='ФИО')
    email = models.EmailField(unique=True, verbose_name='Почта')
    comment = models.TextField(**NULLABLE, verbose_name='Комментарий')
    slug = models.SlugField(unique=True, verbose_name='slug')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE, related_name='customer',
                             verbose_name='Пользователь')

    def __str__(self):
        return f"{self.name} ({self.email})"

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def save(self, *args, **kwargs):
        """Создает уникальный slug для клиента"""

        self.slug = slugify(self.email)
        base_slug = self.slug
        num = 1
        while Customer.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
            self.slug = f'{base_slug}-{num}'
            num += 1
        super().save(*args, **kwargs)


class Message(models.Model):
    """Модель для работы с сообщениями"""

    topic = models.CharField(max_length=200, verbose_name='Тема письма')
    body = models.TextField(**NULLABLE, verbose_name='Содержимое письма')
    slug = models.SlugField(unique=True, verbose_name='slug')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE, related_name='message',
                             verbose_name='Пользователь')

    def __str__(self):
        return self.topic

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def save(self, *args, **kwargs):
        """Создает уникальный slug для сообщения"""

        self.slug = slugify(self.topic)
        base_slug = self.slug
        num = 1
        while Message.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
            self.slug = f'{base_slug}-{num}'
            num += 1
        super().save(*args, **kwargs)


class Mailing(models.Model):
    """Модель для работы с рассылками"""

    date_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')
    start = models.TimeField(default='00:00:00', verbose_name='Время начала рассылки')
    finish = models.TimeField(default='00:00:00', verbose_name='Время окончания рассылки')
    day = models.BooleanField(default=False, verbose_name='Раз в день')
    week = models.BooleanField(default=False, verbose_name='Раз в неделю')
    month = models.BooleanField(default=False, verbose_name='Раз в месяц')
    status = models.CharField(**NULLABLE, max_length=150, verbose_name='Статус рассылки')
    customers = models.ManyToManyField(Customer, related_name='mailing', verbose_name='Клиенты')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, related_name='mailing', **NULLABLE,
                                verbose_name='Сообщение')
    is_active = models.BooleanField(default=True, verbose_name='Активная')
    next_run = models.DateField(**NULLABLE, verbose_name='Дата следующей рассылки')
    slug = models.SlugField(unique=True, verbose_name='slug')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE, related_name='mailing',
                             verbose_name='Пользователь')

    def __str__(self):
        return f"{self.message}"

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ('pk',)
        permissions = [
            (
                'set_is_active_mailing',
                'Can active Рассылка'
            )
        ]

    def save(self, *args, **kwargs):
        """Создает уникальный slug для рассылки"""

        self.slug = slugify(self.message.topic)
        base_slug = self.slug
        num = 1
        while Mailing.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
            self.slug = f'{base_slug}-{num}'
            num += 1
        super().save(*args, **kwargs)


class Log(models.Model):
    """Модель для работы с логами рассылок"""

    date_time_last_attempt = models.DateTimeField(auto_now=True, verbose_name='Дата и время последней попытки')
    attempt_status = models.CharField(max_length=150, verbose_name='Статус попытки')
    mail_server_response = models.CharField(max_length=150, verbose_name='Ответ почтового сервера')
    slug = models.SlugField(unique=True, verbose_name='slug')
    mailing = models.ForeignKey(Mailing, on_delete=models.SET_NULL, **NULLABLE, related_name='log',
                                verbose_name='Рассылка')

    def __str__(self):
        return f"{self.date_time_last_attempt} {self.attempt_status}"

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

    def save(self, *args, **kwargs):
        """Создает уникальный slug для лога"""

        self.slug = slugify(self.attempt_status)
        base_slug = self.slug
        num = 1
        while Log.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
            self.slug = f'{base_slug}-{num}'
            num += 1
        super().save(*args, **kwargs)

service/forms.py
from django import forms

from service.models import Customer, Message, Mailing


class StyleFormMixin:
    """Миксин для формирования стиля форм."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CustomerForm(StyleFormMixin, forms.ModelForm):
    """Форма для работы с клиентами"""

    class Meta:
        model = Customer
        exclude = ('user', 'slug', )


class MessageForm(StyleFormMixin, forms.ModelForm):
    """Форма для работы с сообщениями"""

    class Meta:
        model = Message
        exclude = ('user', 'slug', )


class MailingForm(StyleFormMixin, forms.ModelForm):
    """Форма для работы с рассылками"""

    class Meta:
        model = Mailing
        exclude = ('status', 'is_active', 'next_run', 'user', 'slug', )

    def __init__(self, user, *args, **kwargs):
        """
        Переопределяет поля customers и message таким образом, чтобы в них отображались только клиенты и сообщения
        текущего пользователя.
        """

        super().__init__(*args, **kwargs)
        self.fields['customers'].queryset = Customer.objects.filter(user=user)
        self.fields['message'].queryset = Message.objects.filter(user=user)

service/templates/service/customer_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3>Удаление клиента</h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить клиента "{{ object.name }}"</p>
                <button type="submit" class="btn btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'service:customers'%}">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

service/templates/service/customer_detail.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div class="container py-4">
        <div class="p-5 mb-4 bg-body-tertiary rounded-3">
            <div class="container-fluid py-5">
                <h1 class="display-5 fw-bold">{{ object.name }}</h1>
                <p class="col-md-8 fs-4">{{ object.email }}</p>
                <p class="col-md-8 fs-4">{{ object.comment }}</p>
                <a class="btn btn-primary btn-lg" type="button" href="{% url 'service:customers'%}">Закрыть</a>
                <a class="btn btn-warning btn-lg" type="button" href="{% url 'service:customer_update' object.slug %}">Редактировать</a>
                <a class="btn btn-danger btn-lg" type="button" href="{% url 'service:customer_delete' object.slug %}">Удалить</a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

service/templates/service/customer_form.html
{% extends 'base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Добавить клиента
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    Сохранить
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

service/templates/service/customer_list.html
{% extends 'base.html' %}

{% block content %}
<h2 align="center">Клиенты</h2>
<div class="col12 mb-5">
    <a class="p-2 btn btn-outline-success" href="{% url 'service:customer_create' %}">Добавить клиента</a>
</div>
<table class="table">
    <thead>
    <tr>
        <th scope="col"></th>
        <th scope="col">ФИО</th>
        <th scope="col">Почта</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
        <th scope="row">{{ object.pk }}</th>
        <td>{{ object.name }}</td>
        <td>{{ object.email }}</td>
        <td>
            <a href="{% url 'service:customer' object.slug %}">Смотреть</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

service/templates/service/log_list.html
{% extends 'base.html' %}

{% block content %}
    <h2 align="center">Логи рассылки "{{ mailing }}"</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Дата и время последней попытки</th>
            <th scope="col">Статус попытки</th>
            <th scope="col">Ответ почтового сервера</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <th scope="row">{{ object.pk }}</th>
                <td>{{ object.date_time_last_attempt }}</td>
                <td>{{ object.attempt_status }}</td>
                <td>{{ object.mail_server_response }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

service/templates/service/mailing_detail.html
{% extends 'base.html' %}

{% block content %}
    <h2 align="center">{{ object }}</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Статус</th>
            <th scope="col">Начало</th>
            <th scope="col">Окончание</th>
            <th scope="col">Периодичность</th>
            <th scope="col">Дата следующей отправки</th>
            <th scope="col">Сообщение</th>
            <th scope="col">Получатели</th>
            <th scope="col">Логи</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            {% if object.is_active %}
                <th scope="row">Включена</th>
            {% else %}
                <th scope="row">Отключена</th>
            {% endif %}
            <td>{{ object.status }}</td>
            <td>{{ object.start }}</td>
            <td>{{ object.finish }}</td>
            {% if object.day %}
                <td>Раз в день</td>
            {% elif object.week %}
                <td>Раз в неделю</td>
            {% elif object.month %}
                <td>Раз в месяц</td>
            {% else %}
                <td>Не установлена</td>
            {% endif %}
            <td>{{ object.next_run }}</td>
            <td>
                <a href="{% url 'service:message' object.message.slug %}">Смотреть</a>
            </td>
            <td>
                {% for object in customers %}
                    <li>{{ object }}</li>
                {% endfor %}
            </td>
            <td>
                <a href="{% url 'service:logs' object.slug %}">Смотреть</a>
            </td>
            <td>
                {% if perms.service.change_mailing %}
                    <a class="btn btn-outline-warning"
                       href="{% url 'service:mailing_update' object.slug %}">Редактировать</a>
                {% endif %}
                {% if perms.service.delete_mailing %}
                    <a class="btn btn-outline-danger" href="{% url 'service:mailing_delete' object.slug %}">Удалить</a>
                {% endif %}
            </td>
        </tr>
        </tbody>
    </table>
{% endblock %}

service/templates/service/mailing_form.html
{% extends 'base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Добавить рассылку
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    Сохранить
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

service/templates/service/mailing_list.html
{% extends 'base.html' %}

{% block content %}
    <h2 align="center">Рассылки</h2>
    <div class="col12 mb-5">
        {% if perms.service.add_mailing %}
            <a class="p-2 btn btn-outline-success" href="{% url 'service:mailing_create' %}">Создать рассылку</a>
        {% endif %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'service:report' %}">Отчет проведенных рассылок</a>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Тема</th>
            <th scope="col">Дата и время создания</th>
            <th scope="col">Статус рассылки</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <th scope="row">{{ object.pk }}</th>
                <td>
                    <a href="{% url 'service:mailing' object.slug %}">{{ object }}</a>
                </td>
                <td>{{ object.date_time }}</td>
                <td>{{ object.status }}</td>
                {% if perms.service.set_is_active_mailing %}
                    <td>
                        {% if object.is_active %}
                            <a class="btn btn-outline-danger"
                               href="{% url 'service:mailing_activity' object.slug %}">Отключить</a>
                        {% else %}
                            <a class="btn btn-outline-success"
                               href="{% url 'service:mailing_activity' object.slug %}">Включить</a>
                        {% endif %}
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

service/templates/service/message_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3>Удаление сообщения</h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить сообщение "{{ object.topic }}"</p>
                <button type="submit" class="btn btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'service:messages'%}">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

service/templates/service/message_detail.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="container py-4">
            <div class="p-5 mb-4 bg-body-tertiary rounded-3">
                <div class="container-fluid py-5">
                    <h1 class="display-5 fw-bold">{{ object.topic }}</h1>
                    <p class="col-md-8 fs-4">{{ object.body }}</p>
                    <a class="btn btn-primary btn-lg" type="button" href="{% url 'service:messages' %}">Закрыть</a>
                    {% if perms.service.change_message %}
                        <a class="btn btn-warning btn-lg" type="button"
                           href="{% url 'service:message_update' object.slug %}">Редактировать</a>
                    {% endif %}
                    {% if perms.service.delete_message %}
                        <a class="btn btn-danger btn-lg" type="button"
                           href="{% url 'service:message_delete' object.slug %}">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

service/templates/service/message_form.html
{% extends 'base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Добавить сообщение
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    Сохранить
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

service/templates/service/report.html
{% extends 'base.html' %}

{% block content %}
    <h2 align="center">Отчет проведенных рассылок</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Рассылка</th>
            <th scope="col">Дата и время последней попытки</th>
            <th scope="col">Статус попытки</th>
            <th scope="col">Ответ почтового сервера</th>
            <th scope="col">Дата следующей отправки</th>
        </tr>
        </thead>
        <tbody>
        {% for object in mailings_done %}
            {% if user.is_staff or object.mailing.user == user %}
                <tr>
                    <th scope="row">{{ object.pk }}</th>
                    <td>
                        {% if object.mailing %}
                            <a href="{% url 'service:mailing' object.mailing.slug %}">{{ object.mailing }}</a>
                        {% else %}
                            Удалена
                        {% endif %}
                    </td>
                    <td>{{ object.date_time_last_attempt }}</td>
                    <td>{{ object.attempt_status }}</td>
                    <td>{{ object.mail_server_response }}</td>
                    <td>{{ object.mailing.next_run }}</td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

service/templates/service/service_detail.html
{% extends 'service/base.html' %}

{% block content %}
<main>
    <div class="container py-4">
        <div class="p-5 mb-4 bg-body-tertiary rounded-3">
            <div class="container-fluid py-5">
                <h3>Получатели</h3>
                {% for object in customers %}
                <li>{{ object }}</li>
                {% endfor %}
                <h3>Тема рассылки</h3>
                <p class="col-md-8 fs-4">{{ object.message }}</p>
                <h3>Контент</h3>
                <p class="col-md-8 fs-4">{{ object.message.body }}</p>
                <p>Начало рассылки: {{ object.start }}</p>
                <p>Окончание рассылки: {{ object.finish }}</p>
                <h5>Периодичность рассылки</h5>
                {% if object.day %}
                <p>-раз а день</p>
                {% elif object.week %}
                <p>-раз а неделю</p>
                {% elif object.month %}
                <p>-раз а месяц</p>
                {% else %}
                <p>-не установлена</p>
                {% endif %}
                <p class="col-md-8 fs-4">{{ object.periodicity }}</p>
                <p class="col-md-8 fs-4">{{ object.log }}</p>
                <a class="btn btn-primary btn-lg" type="button" href="{% url 'service:services'%}">Закрыть</a>
                <a class="btn btn-warning btn-lg" type="button" href="{% url 'service:service_update' object.pk %}">Редактировать</a>
                <a class="btn btn-danger btn-lg" type="button" href="{% url 'service:service_delete' object.pk %}">Удалить</a>
            </div>
        </div>
    </div>
</main>
{% endblock %}+

service/templates/service/service_form.html
{% extends 'service/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Добавить рассылку
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    Сохранить
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}